# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b51576c4c044c73979da098a5c55a6aa"
name = "ECS Delivery Estimator"
application_url = "https://estimator-app-live-web-repo.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"
 [[webhooks.subscriptions]]
 uri = "https://estimator-app-live-web-repo.onrender.com/api/webhooks"
 topics = [ "app/uninstalled" ]
 compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_themes,write_products,read_locales,read_markets,read_orders,read_shipping,write_script_tags,read_inventory"

[auth]
redirect_urls = [
  "https://estimator-app-live-web-repo.onrender.com/auth/callback",
  "https://estimator-app-live-web-repo.onrender.com/auth/shopify/callback",
  "https://estimator-app-live-web-repo.onrender.com/api/auth/callback"
]

